chore: update rattler and remove archspec for now
prefix-dev/pixi pull request #1103
Opened 2024-04-02 09:29 UTC by wolfv

2024-04-03 10:35 UTC, ruben-arts requested changes

2024-04-03 10:35 UTC, ruben-arts commented on src/project/manifest/system_requirements.rs
> -    pub archspec: Option<String>,
Removing this is a breaking change, I would like to move this into a (deprecation) warning if used.

2024-04-04 09:17 UTC, wolfv commented
@ruben-arts I reverted the changes so that the archspec is still parsed if present. It will emit a deprecation warning.

2024-04-04 13:41 UTC, ruben-arts approved these changes

2024-04-04 14:04 UTC, merged