feat: add env to activation table
prefix-dev/pixi pull request #1156
Opened 2024-04-10 15:13 UTC by ruben-arts

Not sure about this addition. Would expect it to be a lot smarter but now it just sets simple environment variables. 

I would expect it to expand variables if you would do:
```toml
[activation.env]
PATH = "bla/bli/blu:$PATH"
```

2024-04-12 08:00 UTC, ruben-arts commented
@wolfv What do you think? Merge this already (after adding docs) or figuring out a better parsing solution for the variables?

2024-04-18 08:38 UTC, ruben-arts commented
After merging #972 This feature is to simple and will cause confusion

2024-04-25 20:02 UTC, ruben-arts commented
@baszalmstra Do you have some smart ideas on how to easily and in a cross-platform way, add these env vars?
Specifically reusing existing variables:
```toml
[activation]
env = { PATH = "$PIXI_PROJECT_ROOT/extra/path:$PATH", MODEL_LOCATION = "$PIXI_PROJECT_ROOT/models"}
```

One of my ideas would be parsing the strings ourself and use rusts `std::env::var()`, what do you think about that?

2024-04-26 09:33 UTC, ruben-arts commented
Will have to try it out as they seem to just use the direct naming but they do support taskfiles per OS.

2024-05-11 07:13 UTC, beenje commented
> After merging #972 This feature is to simple and will cause confusion

Sometimes you really want some variables per environment.
It can be done with activation script, but I personally don't like having to add 2 extra scripts (.sh and .bat) to the repo just for that. Could also need more scripts in case of multi-environments. It's much nicer to be able to keep that in the `pixi.toml` file.

I currently use the variables per task but when you have several tasks using the same variable(s), it becomes quite verbose. And you might want a variable to be set without defining a specific task.
I think having the same feature as variable per task but per env would be a nice addition. I also really like that those are default you can overwrite from the shell.

2024-05-13 06:46 UTC, ruben-arts commented
He @beenje, Thanks for the input. I completely agree with you. Still need to get back to this PR to test the above discussed change.

2024-05-22 07:56 UTC, baszalmstra requested changes

2024-05-22 07:56 UTC, baszalmstra commented on src/project/manifest/activation.rs
> +    pub env: Option<HashMap<String, String>>,
I think in the future it might become important to retain the order of insertion. So perhaps using an `IndexMap` is more appropriate.

2024-05-22 07:56 UTC, baszalmstra commented on src/project/manifest/feature.rs
> +    pub fn activation_env(&self, platform: Option<Platform>) -> Option<&HashMap<String, String>> {
Please add a comment.

2024-05-24 12:44 UTC, baszalmstra approved these changes

2024-05-24 15:38 UTC, merged