add authentication subcommand
prefix-dev/pixi pull request #120
Opened 2023-06-20 15:24 UTC by wolfv

So far this is just a simple subcommand to store login information

2023-06-21 13:54 UTC, ruben-arts commented
Not sure how to test this. I tried a private channel on prefix.dev but that does not seems to work, either because of prefix.dev or pixi. Error I get:
```
ERROR rattler_repodata_gateway::fetch: error=HTTP status client error (403 Forbidden) for url (https://repo.prefix.dev/ruben-arts/noarch/repodata.json)
ERROR rattler_repodata_gateway::fetch: error=HTTP status client error (403 Forbidden) for url (https://repo.prefix.dev/ruben-arts/linux-64/repodata.json)
error: failed to fetch repodata from channels

Caused by:
    HTTP status client error (403 Forbidden) for url (https://repo.prefix.dev/ruben-arts/noarch/repodata.json)
```
Those repodata jsons are indeed not available for me, even in the browser. 

I added @wolfv @baszalmstra @tdejager to the channel so you should be able to test it.

2023-06-22 07:07 UTC, ruben-arts requested changes

2023-06-22 07:07 UTC, ruben-arts commented on src/cli/auth.rs
> +    /// The host to authenticate with
It would be nice to have an example. I was trying to put a `https://host/channel` in there. Using repo.prefix.dev as an example would help.

2023-06-22 07:07 UTC, ruben-arts commented on src/cli/auth.rs
> +    /// The token to use (for bearer authentication)
Not sure if bearer authentication is going to help the user. Maybe just name it API token for prefix.dev.

2023-06-22 14:45 UTC, ruben-arts commented
I'm okay with merging this but I see some low-hanging fruit to improve the UX some more:
- `pixi auth login` should check if the login actually works by pinging the host or something. 
- `pixi auth login` x2 should tell its overwriting existing credentials
- `pixi auth logout bla` should tell me if it doesn't do anything as I might have a typo in which case it didn't do anything. 
- `pixi auth check` would be very nice to have to check if you can still access all your hosts.

2023-06-22 14:53 UTC, wolfv commented
Maybe let's merge and iterate? I think we should also fix what we store (eg. host or host + subdomain) but that might be better to fix in rattler vs. here).

2023-06-23 09:14 UTC, merged