feat: Add nushell completion
prefix-dev/pixi pull request #1599
Opened 2024-07-10 07:07 UTC by Hofer-Julian

- Add nushell completion
- Stop guessing shell, and make `--shell` required
- Adapt instructions

I have a version local that still tries to guess the shell from the `$SHELL` env var. But it made the code much more verbose, and I am not a fan of that behavior. On my system, `$SHELL` gives `/bin/bash` even though I use nushell.

I also adapted the instructions to stop suggesting that your choice of shell is platform dependent. Every listed shell can be used on Windows and vice versa.

2024-07-10 07:53 UTC, baszalmstra requested changes
A a rule of thumb I think we should always prefer sane defaults over having to specify a value explicitly because its something else to understand or learn.

I think having to specify the `--shell` explicitly moves the burden to specify the shell to the user whereas most of the time we can just detect it. If the shell is not properly detected I would consider that a bug instead. Perhaps you can [use the logic in `rattler_shell`](https://docs.rs/rattler_shell/latest/rattler_shell/shell/enum.ShellEnum.html#method.from_env) to detect the active shell? I think it contains more logic than just checking `$SHELL`? It also properly detects the shell when using `pixi shell`. I would be fine with erroring out if the shell cannot be detected though, instead of defaulting to bash.

I also think that although you are technically correct that any shell can be used on Windows we should still keep the tabs in the documentation. I think most users will not be running fish or zsh under windows. And the ones that do will most likely also understand to look under the linux tab. Or we could add a note about it. 

Besides that for a starting user having just a single line (especially on Windows) is much less scary than having a whole bunch of echo statements. We want to make it as easy as possible for users.

2024-07-10 08:35 UTC, Hofer-Julian commented
> A a rule of thumb I think we should always prefer sane defaults over having to specify a value explicitly because its something else to understand or learn.

In general, I agree. For this specific case, I argue we gain nothing.
The actual command to use completions is shell specific anyway.
I don't see how `echo 'eval "$(pixi completion)"' >> ~/.bashrc` is better than `echo 'eval "$(pixi completion --shell bash)"' >> ~/.bashrc`. Especially if the former is less robust.


> I also think that although you are technically correct that any shell can be used on Windows we should still keep the tabs in the documentation. I think most users will not be running fish or zsh under windows. And the ones that do will most likely also understand to look under the linux tab. Or we could add a note about it.

Thanks for the feedback, I restructured the docs and like it much more now.
Let me know if you agree.

2024-07-11 08:08 UTC, baszalmstra approved these changes
Ok you convinced me, lets just merge and see if someone complains.

Ill let @ruben-arts review the documentation changes. They LGTM.

2024-07-13 16:27 UTC, ruben-arts commented
![image](https://github.com/user-attachments/assets/7083da26-393c-4885-96c9-a5f9dc34b1b6)
Any idea why the help is double and prefixing the login and logout?

2024-07-13 21:00 UTC, Hofer-Julian commented
> ![image](https://private-user-images.githubusercontent.com/12893423/348484236-7083da26-393c-4885-96c9-a5f9dc34b1b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MDQ1OTgsIm5iZiI6MTcyMDkwNDI5OCwicGF0aCI6Ii8xMjg5MzQyMy8zNDg0ODQyMzYtNzA4M2RhMjYtMzkzYy00ODg1LTk2YzktYTVmOWRjMzRiMWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDIwNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOTM0NjE3YmM4ZjcwNzI0NzY5OWQ4NDAwMGJmYWJiMmI4YjFhMGMxNjc3YjdkNDM0ZWRjOWNmOTc0M2RmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzMMPwr12sPFNAlR_mZOZ8t_ZvBC9xl7WMqPAlCEgR0) Any idea why the help is double and prefixing the login and logout?

No, but I found similar bugs in rattler-build. Still have to check if it's our or clap_complete_nushell's fault.

Can you reproduce it with other shells?

2024-07-15 07:00 UTC, tdejager commented
> > ![image](https://private-user-images.githubusercontent.com/12893423/348484236-7083da26-393c-4885-96c9-a5f9dc34b1b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MDQ1OTgsIm5iZiI6MTcyMDkwNDI5OCwicGF0aCI6Ii8xMjg5MzQyMy8zNDg0ODQyMzYtNzA4M2RhMjYtMzkzYy00ODg1LTk2YzktYTVmOWRjMzRiMWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDIwNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOTM0NjE3YmM4ZjcwNzI0NzY5OWQ4NDAwMGJmYWJiMmI4YjFhMGMxNjc3YjdkNDM0ZWRjOWNmOTc0M2RmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzMMPwr12sPFNAlR_mZOZ8t_ZvBC9xl7WMqPAlCEgR0) Any idea why the help is double and prefixing the login and logout?
> 
> No, but I found similar bugs in rattler-build. Still have to check if it's our or clap_complete_nushell's fault.
> 
> Can you reproduce it with other shells?

Well they are valid commands and provide the help for those given commands. E.g. `pixi auth help login` gives me: 

```
Store authentication information for a given host

Usage: pixi auth login [OPTIONS] <HOST>

Arguments:
  <HOST>  The host to authenticate with (e.g. repo.prefix.dev)
```

So in that case it seems the docs-string is just wrong, and we might need to `ignore` these commands in the autcomplete if that possible?

2024-07-15 07:38 UTC, Hofer-Julian commented
> So in that case it seems the docs-string is just wrong, and we might need to ignore these commands in the autcomplete if that possible?

Nice find @tdejager.
Sounds to me like we can merge this PR then and create a follow-up issue for the issues you found. Agreed?

2024-07-16 09:45 UTC, merged