fix: take feature channels in consideration
prefix-dev/pixi pull request #2038
Opened 2024-09-11 15:53 UTC by nichmor

fixes: https://github.com/prefix-dev/pixi/issues/1988

2024-09-11 17:57 UTC, nichmor commented
> Can you also add a test?

yes! will add it

2024-09-13 13:42 UTC, tdejager requested changes

2024-09-13 13:42 UTC, tdejager commented on src/project/mod.rs
> +    fn test_mapping_check_also_feature_channels() {
```suggestion
    fn test_mapping_ensure_feature_channels_also_checked() {
```

2024-09-13 13:42 UTC, tdejager commented on src/project/snapshots/pixi__project__tests__mapping_check_also_feature_channels.snap
> +Defined conda-pypi-map channel: non-existing-channel is missing from the channels, which are: conda-forge, pytorch
I think we can improve this message with:

```suggestion
conda-pypi-map is defined: the `non-existing-channel` is missing from the channels array, which currently are: conda-forge, pytorch
```

2024-09-13 14:00 UTC, tdejager requested changes
Would you mind adding a custom `thiserror` and using miette a bit higher up the chain, this would require some refactoring though.

2024-09-13 14:15 UTC, baszalmstra approved these changes

2024-09-16 08:18 UTC, tdejager approved these changes

2024-09-16 08:18 UTC, merged