perf: quick validation of enviroment on activating commands
prefix-dev/pixi pull request #2400
Opened 2024-11-01 08:32 UTC by ruben-arts

This pr will add a hash of the lock file to the `EnvironmentFile` (`.pixi/envs/default/conda-meta/pixi`)

It will look like this:
```json
{
  "manifest_path": "/home/rarts/dev/pixi/pixi.toml",
  "environment_name": "default",
  "pixi_version": "0.34.0",
  "environment_lock_file_hash": "4f36ee620f10329d"
}
```
And that hash will be compared with the current lockfile on `pixi run` `pixi shell` `pixi shell-hook`.

Profile result:
```shell
❯ hyperfine "pixi run echo" "old-pixi run echo"
Benchmark 1: pixi run echo
  Time (mean ± σ):     381.6 ms ±  22.1 ms    [User: 193.8 ms, System: 246.3 ms]
  Range (min … max):   344.5 ms … 414.3 ms    10 runs
 
Benchmark 2: old-pixi run echo
  Time (mean ± σ):     868.2 ms ±  58.2 ms    [User: 480.0 ms, System: 557.0 ms]
  Range (min … max):   791.1 ms … 950.8 ms    10 runs
 
Summary
  pixi run echo ran
    2.28 ± 0.20 times faster than old-pixi run echo
```

2024-11-04 09:14 UTC, ruben-arts commented on src/cli/install.rs
> +        update_prefix(&environment, args.lock_file_usage.into(), false, true).await?;
Change the booleans into an enum so it's readable

2024-11-05 10:04 UTC, Hofer-Julian requested changes
Looks good! I can also reproduce the speed-up on my machine 😄

I added a few suggestions.

2024-11-05 10:04 UTC, Hofer-Julian commented on tests/integration/test_run_cli.py
> +    import glob
```suggestion
```

Let's use the glob functionality provided by `pathlib` instead.
In general, I would also prefer top-level imports unless there's a good reason for it

2024-11-05 13:13 UTC, ruben-arts commented on src/environment.rs
> +        LockedEnvironmentHash(format!("{:x}", hasher.finish()))
The reason is that that was what was used in the `EnvironmentHash`, but maybe it should be extended to also include "package hash" level detail. Ill give it a go as it was missed by me.

2024-11-05 13:14 UTC, ruben-arts commented on src/lock_file/update.rs
> +            if let Ok(Some(environment_file)) = read_environment_file(&environment.dir()) {
Smart!

2024-11-05 13:31 UTC, ruben-arts commented on tests/integration/test_run_cli.py
> +    import glob
Fixed in [`1b2ade3` (#2400)](https://github.com/prefix-dev/pixi/pull/2400/commits/1b2ade3bf11712ed2cdd95ab78e1835c5b2067b1)

2024-11-06 10:33 UTC, Hofer-Julian approved these changes
Great work @ruben-arts!

2024-11-06 10:36 UTC, merged