feat: add cli modifications of the system requirements
prefix-dev/pixi pull request #2765
Opened 2024-12-24 14:12 UTC by ruben-arts

## Why?
We want to work towards more automation around the system requirements. Most likely, a part of that is automated serialization for the manifest. This is a preparation for that. And secondly, it's better to have CLI options for DX and especially for tutorial. 

## Feature
Allows users to run:
```
pixi project system-requirements add linux 5.13

pixi project system-requirements add glibc 2.12

pixi project system-requirements add cuda 12.6
```

2024-12-30 10:03 UTC, Hofer-Julian requested changes
This looks like a useful addition @ruben-arts!

Apart from my comments, I would also like to see an integration test, testing the CLI

2024-12-30 10:03 UTC, Hofer-Julian commented on src/cli/project/system_requirements/mod.rs
> +// pub mod remove;
```suggestion
```

2024-12-30 10:03 UTC, Hofer-Julian commented on src/cli/project/system_requirements/mod.rs
> +    // Remove(remove::Args),
```suggestion
```

Let's not leave behind commented out code :)

2024-12-30 10:03 UTC, Hofer-Julian commented on src/cli/project/system_requirements/mod.rs
> +        // Command::Remove(args) => remove::execute(project, args).await,
```suggestion
```

2024-12-30 10:03 UTC, Hofer-Julian commented on crates/pixi_manifest/src/manifests/source.rs
> +    fn test_add_system_requirement_environment(#[case] mut source: ManifestSource) {
I think this test could be split into multiple tests

2025-01-03 10:24 UTC, ruben-arts commented on src/cli/project/system_requirements/add.rs
> +            )?;
Changed this

2025-01-03 13:57 UTC, baszalmstra commented on crates/pixi_manifest/src/manifests/source.rs
> +    fn test_add_system_requirement_environment(#[case] mut source: ManifestSource) {
I think Julian refers to the different cases that are tested in this test. E.g. Adding empty requirements, adding a single requirement, etc.

2025-01-03 14:53 UTC, ruben-arts commented on crates/pixi_manifest/src/manifests/source.rs
> +    fn test_add_system_requirement_environment(#[case] mut source: ManifestSource) {
Aaaaah changed that!

2025-01-03 14:53 UTC, merged