Feat/remove command
prefix-dev/pixi pull request #483
Opened 2023-11-21 16:43 UTC by Wackyator

This adds a `remove`/`rm` subcommand to pixi which removes dependencies from the following tablles in the toml file:
- `[dependencies]`
- `[host-dependencies]`
- `[build-dependencies]` 
- `[target.{platform}.dependencies]`
- `[target.{platform}.host-dependencies]`
- `[target.{platform}.build-dependencies]`

Closes #49

2023-11-22 20:22 UTC, ruben-arts requested changes
The UX is really good, adding the updating of the prefix is a requirement from my point of view though.

2023-11-22 20:22 UTC, ruben-arts commented on src/project/mod.rs
> +#[allow(unused)]
I guess this is not needed anymore?

2023-11-22 20:22 UTC, ruben-arts commented on src/project/mod.rs
> +    pub fn remove_dependency(
I think it is valuable to add some small tests to show that this does the correct modification as you showed on discord.
Something like this:
```rust
#[test]
fn test_remove_target_dependencies() {
  // Using known files in the project so the test succeed including the file check.
  let file_contents = r#"
      [dependencies]
      numpy = "*"

      [target.win-64.dependencies]
      numpy = "*"

      [target.linux-64.build-dependencies]
      numpy = "*"
      "#;

  let manifest = toml_edit::de::from_str::<ProjectManifest>(&format!(
      "{PROJECT_BOILERPLATE}\n{file_contents}"
  ))
      .unwrap();
  let mut project = Project::from_manifest(manifest);
  project.remove_target_dependency(&PackageName::try_from("numpy").unwrap(), &SpecType::Build ,&Platform::Linux64).unwrap();
  assert_debug_snapshot!(project.manifest);
}
```

2023-11-28 08:54 UTC, baszalmstra commented on src/cli/remove.rs
> +        .collect::<Vec<_>>();
This is just a `for` loop right? You are not using the result at all, so collecting seems wasteful.

2023-11-28 08:54 UTC, baszalmstra commented on src/cli/remove.rs
> +        .collect::<Vec<_>>();
Same

2023-11-28 08:54 UTC, baszalmstra commented on src/project/mod.rs
> +                self.save()?;
I would prefer that this method doesn't implicitly save the project to disk. I'd rather this is pulled out and done manually.

2023-11-28 08:54 UTC, baszalmstra commented on src/project/mod.rs
> +        self.save()?;
Same for this

2023-11-28 10:40 UTC, baszalmstra approved these changes

2023-11-28 10:41 UTC, merged