add lightgbm demo
prefix-dev/pixi pull request #492
Opened 2023-11-24 00:57 UTC by partrita

I just made simple code for ML.
Thanks in advance.

2023-11-24 12:42 UTC, ruben-arts requested changes
Awesome @partrita Thank you!
Left a few small requests.

2023-11-24 12:42 UTC, ruben-arts commented on examples/lightgbm/pixi.toml
> +platforms = ["linux-64"]
```suggestion
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
```
We always try to make the examples as multi platform as possible. We can test it on all systems. Adding this does require to rerender the `pixi.lock` Could you do that?

2023-11-24 12:42 UTC, ruben-arts commented on examples/lightgbm/pixi.toml
> +[tasks]
```suggestion
[tasks]
start = "python main.py"
```
We try to always add a `start` command :smile:

2023-11-24 12:42 UTC, ruben-arts commented on examples/lightgbm/README.md
> +pixi run python main.py
```suggestion
pixi run start
```
After the change in the `pixi.toml`

2023-11-28 09:43 UTC, ruben-arts commented
He @partrita This looks good, could you also commit the updated the `pixi.lock`. I you don't have it yet you can run `pixi install` and then push the changes!

2023-11-29 00:11 UTC, partrita commented
> He @partrita This looks good, could you also commit the updated the `pixi.lock`. I you don't have it yet you can run `pixi install` and then push the changes!

Ok, I just commited. Thanks!

2023-11-29 08:21 UTC, ruben-arts approved these changes

2023-11-29 08:24 UTC, ruben-arts commented
Sorry, I forgot to run start CI on your PR. You should be able to test this locally with `pixi run lint`.

2023-11-30 05:03 UTC, partrita commented
> Sorry, I forgot to run start CI on your PR. You should be able to test this locally with `pixi run lint`.

`pixi run lint` command was not working, I do this.

```bash
pixi global install pre-commit
pre-commit install //in project folder
git add .
git commit -m ""
git push
```

Thanks!

2023-11-30 13:26 UTC, merged